server:
  port: 8000

keycloak:
  resource: springboot-keycloak-client
  realm: springboot-keycloak
  auth-server-url: https://localhost:8443/auth
  public-client: true
  bearer-only: true
  ssl-required: false