server:
  port: 8000
  ssl:
    enabled: false

keycloak:
  resource: springboot-keycloak-client
  realm: springboot-keycloak
  auth-server-url: http://65.2.6.253:8080/auth
  public-client: true
  bearer-only: true
  ssl-required: NONE